// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ParyanPerfume.Migrations
{
    [DbContext(typeof(ParyanPerfumeDbContext))]
    [Migration("20250517163346_EditNameOfTableToPerfume2")]
    partial class EditNameOfTableToPerfume2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("DataLayer.Categories", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("category");
                });

            modelBuilder.Entity("DataLayer.Perfumes", b =>
                {
                    b.Property<int>("PerfumeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("PerfumeBrand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PerfumeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PerfumeSex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PricePer100gram")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PricePerKilogram")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowInSlider")
                        .HasColumnType("INTEGER");

                    b.HasKey("PerfumeId");

                    b.HasIndex("CategoryId");

                    b.ToTable("perfume");
                });

            modelBuilder.Entity("DataLayer.Perfumes", b =>
                {
                    b.HasOne("DataLayer.Categories", "category")
                        .WithMany("perfume")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("DataLayer.Categories", b =>
                {
                    b.Navigation("perfume");
                });
#pragma warning restore 612, 618
        }
    }
}
