// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ParyanPerfume.Migrations
{
    [DbContext(typeof(ParyanPerfumeDbContext))]
    partial class ParyanPerfumeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("DataLayer.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("ProductType").HasValue("Product");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DataLayer.Bottle", b =>
                {
                    b.HasBaseType("DataLayer.Product");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityInCarton")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityInPackaging")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Volume")
                        .HasColumnType("REAL");

                    b.ToTable("Products", t =>
                        {
                            t.Property("QuantityInCarton")
                                .HasColumnName("Bottle_QuantityInCarton");

                            t.Property("QuantityInPackaging")
                                .HasColumnName("Bottle_QuantityInPackaging");
                        });

                    b.HasDiscriminator().HasValue("Bottle");
                });

            modelBuilder.Entity("DataLayer.Fixator", b =>
                {
                    b.HasBaseType("DataLayer.Product");

                    b.Property<bool>("IsAlcoholFree")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PricePer20Liters")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowInSlider")
                        .HasColumnType("INTEGER");

                    b.ToTable("Products", t =>
                        {
                            t.Property("ShowInSlider")
                                .HasColumnName("Fixator_ShowInSlider");
                        });

                    b.HasDiscriminator().HasValue("Fixator");
                });

            modelBuilder.Entity("DataLayer.Perfume", b =>
                {
                    b.HasBaseType("DataLayer.Product");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PricePer100gram")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowInSlider")
                        .HasColumnType("INTEGER");

                    b.ToTable("Products", t =>
                        {
                            t.Property("ShowInSlider")
                                .HasColumnName("Perfume_ShowInSlider");
                        });

                    b.HasDiscriminator().HasValue("Perfume");
                });

            modelBuilder.Entity("DataLayer.Pocket", b =>
                {
                    b.HasBaseType("DataLayer.Product");

                    b.Property<int>("QuantityInCarton")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityInPackaging")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowInSlider")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Pocket");
                });
#pragma warning restore 612, 618
        }
    }
}
